### ISSUE TITLE
Write generic APIs for seamless use

### ISSUE THREAD

**Issue by Sayeed97** [Sayeed97/UNO-ESP8266-I2C#4]
We want to make this API available for public use for Arduino UNO and ESP8266.

Useful References:

1. Arduino Guide - https://docs.arduino.cc/learn/contributions/arduino-creating-library-guide/
2. API Styling Guidelines By Arduino Community - https://docs.arduino.cc/learn/contributions/arduino-library-style-guide/
3. Hackster.io Guide - https://www.hackster.io/mcmchris/create-and-publish-your-own-arduino-library-907a41

**Comment by charantejaabbavathini** [comment]
Closing this issue because the ESP does not have support for slave mode.
