### ISSUE TITLE
Publish the new library for both Arduino UNO and ESP8266

### ISSUE THREAD

**Issue by Sayeed97** [Sayeed97/UNO-ESP8266-I2C#5]

**Comment by Sayeed97** [comment]
We will need to add our SSH keys to this repository to push a new library to the GitHub repository to have read/write access.

References -

SSH key generation: https://stackoverflow.com/questions/2643502/git-how-to-solve-permission-denied-publickey-error-when-using-git

SSH key association with the GitHub: https://stackoverflow.com/questions/57971890/how-can-i-use-ssh-to-push-my-repository-to-github

**Comment by charantejaabbavathini** [comment]
Closing this issue because the ESP does not have support for slave mode.
